// ============================================
// PRODUCT DATA FILE - EDIT THIS FILE TO ADD/MODIFY PRODUCTS
// ============================================
// Structure:
// {
//     category: "Category Name",
//     subcategory: "Subcategory Name",  // Use if only one subcategory
//     products: ["Product 1", "Product 2"]
// }
// OR for multiple subcategories:
// {
//     category: "Category Name",
//     subcategories: [
//         { name: "Subcategory 1", products: ["Product A", "Product B"] },
//         { name: "Subcategory 2", products: ["Product C", "Product D"] }
//     ]
// }

const products = [
    {
        category: "Namkeen",
        subcategory: "Haldiram's",
        products: [
            "All In One 1 Kg",
            "All In One 200 G",
            "All In One 400 G",
            "Aloo Bhujia 1 Kg",
            "Aloo Bhujia 200 G",
            "Aloo Bhujia 400 G",
            "Aloo Mix 150 G",
            "Bhel Puri Chutney",
            "Bhelpuri 200 G",
            "Bhujia 1 Kg",
            "Bhujia 200 G",
            "Bhujia 400 G",
            "Bombay Mix 200 G",
            "Boondi 200 G",
            "Chakoli 200 G",
            "Chana Cracker 200 G",
"Chana Jor Garam 160 G",
"Chana Nut 200 G",
"Chanachur 200 G",
"Chatpata Dal 200 G",
"Chatpata Mix 200 G",
"Chilli Chatak Lachha",
"Chutney Sev 150 G",
"Cornflakes Mix 200 G",
"Diet Chiwda 150 G",
"Diet Mixture 150 G",
"Diet Murmura 150 G",
"Falahari Mixture 200 G",
"Fatafat Bhel 150 G",
"Gathiya 200 G",
"Golden Mix 150 G",
"Gujarati Mixture 200 G",
"Gup Shup Chana 200 G",
"Gup Shup Peanuts 200 G",
"Heeng Jeera Peanut 200 G",
"Kachori 200 G",
"Kaju Mixture 200 G",
"Kashmiri Mix 200 G",
"Kerala Mixture 200 G",
"Khatta Meetha 1 Kg",
"Khatta Meetha 200 G",
"Khatta Meetha 460 G",
"Macaroni 200 G",
"Macaroni 450 G",
"Macroni 900 G",
"Madras Mixture 200 G",
"Malai Sev 200 G",
"Marwari Bhujia 150 G",
"Masala Boondi 200 G",
"Masala Peanuts 200 G",
"Mathri 200 G",
"Medium Masala Papad 400 G",
"Methi Sev 200 G",
"Mini Bhakhar Badi 200 G",
"Mint Lacha 200 G",
"Moong Dal 200 G",
"Moong Dal 400 G",
"Murukku 200 G",
"Navrattan 200 G",
"Navrattan 400 G",
"Nimbu Masala 200 G",
"Nut Cracker 200 G",
"Nut Cracker 400 G",
"Palak Sev 200 G",
"Panchrattan 200 G",
"Panchrattan 400 G",
"Party Mix 150 G",
"Plain Bhujia 230 G",
"Plain Bhujia 400 G",
"Punjabi Papad 200 G",
"Punjabi Tadka 200 G",
"Rasgulla 1 Kg",
"Ratlami Sev 200 G",
"Roasted Crush Peanut 200 G",
"Roasted Peanut 200 G",
"Roasted Peanuts Hing Jeera 140 G",
"Roasted Peanuts Tandoori 140 G",
"Roasted Vermicelli 425 G",
"Sabji Pakoda 150 G",
"Sabudana Mix 150 G",
"Salted Peanuts 200 G",
"Salted Peanuts 400 G",
"Samosa 200 G",
"Shahi Dal Biji 200 G",
"Shahi Mixture 200 G",
"Soystix 150 G",
"Teekha Meetha 200 G",
"Vermicelli 500 G",
"Vermicilli 900 G",
        ]
    },
    
];
